name: Go-CI

on: [push, pull_request]

jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: go1.12  linters
      uses: shoukoo/golang-pipeline/go1.12/linter@master
      with:
        GOLINT: on
        GOLINTPATH: pkg/controller
        MISSPELL: on
    - name: go1.12 test
      uses: shoukoo/golang-pipeline/go1.12/test@master